name: tag
on:
  push:
    tags:
    - "*"
jobs:
  release:
    needs: [build, build-nix, pre-commit]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.18.0
