name: tag
on:
  push:
    tags:
      - "*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.18.0
        with:
          generateReleaseNotes: true
  call_workflow:
    needs: [release]
    permissions:
      contents: write
    strategy:
      matrix:
        type: [iemod, windows, linux, macos]
    uses: InfinityTools/WeiduModPackagerLibrary/.github/workflows/WeiduModPackagerLibrary.yml@master
    with:
      type: ${{ matrix.type }}
      architecture: amd64
      suffix: ${{ github.ref_name }}
      naming: tp2
      weidu_version: latest
      prefix_windows: win
      prefix_linux: lin
      prefix_macos: mac
      multi_platforms: 'linux:macos:windows'
      multi_autoupdate: true
      case_sensitive: false
      beautify: true
      lower_case: false
      include_submodules: 'false'
